### ISSUE TITLE
Create dummy json data

### ISSUE THREAD

**Issue by Shubhamrawat5** [PVX-COMMUNITY/admin-dashboard#5]
Make a dummy json data for the tables.
Make a folder having all the json files like members.json, groups.json, etc.

**Comment by Shubhamrawat5** [comment]
Make a folder having all the json files like members.json, groups.json, etc.

**Comment by ni3mumbaikar** [comment]
Closed with https://github.com/PVX-COMMUNITY/admin-dashboard/pull/14
